[package]
name = "gstools-core"
version = "1.3.0"
authors = ["Lennart Schüler <lennart.schueler@ufz.de>"]
edition = "2021"
description = "The core functions of GSTools"
readme = "README.md"
homepage = "https://geostat-framework.org/#gstools"
repository = "https://github.com/GeoStat-Framework/GSTools-Core"
documentation = "https://docs.rs/gstools-core"
license = "LGPL-3.0-or-later"
categories = ["science", "mathematics"]
keywords = ["geostatistics", "srf", "kriging", "variogram", "python"]
exclude = ["dist/", ".*"]

[lib]
name = "gstools_core"
crate-type = ["cdylib", "rlib"]
bench = false

[profile.release]
panic = "abort"
lto = true
codegen-units = 1

[profile.bench]
debug = true
lto = true
codegen-units = 1

[dependencies]
pyo3 = { version = "0.28", features = ["abi3-py38", "extension-module"] }
numpy = "0.28"
ndarray = { version = "0.17", features = ["rayon", "approx"] }
rayon = "1.10"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
approx = "0.5"
ndarray-rand = "0.16"

[[bench]]
name = "main"
harness = false

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex-header.html"]
